Machine A:
  Initial_global_state:
    - "S0"
  States:
    - "S0"
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S1"
      event: "-1"
      channel: "Machine B"
    - from: "S0"
      to: "S1"
      event: "+3"
    - from: "S1"
      to: "S2"
      event: "-2"
      channel: "Machine B"
    - from: "S1"
      to: "S2"
      event: "+3"
    - from: "S1"
      to: "S3"
      event: "+4"
    - from: "S3"
      to: "S2"
      event: "+3"
    - from: "S2"
      to: "S0"
      event: "+3"
Machine B:
  Initial_global_state:
    - "S0"
  States:
    - "S0"
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S1"
      event: "-3"
      channel: "Machine A"
    - from: "S0"
      to: "S2"
      event: "+1"
    - from: "S1"
      to: "S2"
      event: "+1"
    - from: "S2"
      to: "S0"
      event: "+2"
    - from: "S2"
      to: "S3"
      event: "+1"
    - from: "S3"
      to: "S2"
      event: "-4"
      channel: "Machine C"
Machine C:
  Initial_global_state:
    - "S0"
  States:
    - "S0"
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S1"
      event: "-1"
      channel: "Machine B"
    - from: "S0"
      to: "S1"
      event: "+3"
    - from: "S1"
      to: "S2"
      event: "-4"
      channel: "Machine A"
    - from: "S1"
      to: "S2"
      event: "+3"
    - from: "S1"
      to: "S3"
      event: "+4"
    - from: "S3"
      to: "S2"
      event: "+3"
    - from: "S2"
      to: "S0"
      event: "+3"
