Machine A:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S1"
      to: "S2"
      input: "+a"
      event: "Event name 01"
    - from: "S1"
      to: "S2"
      input: "+b"
      event: "Event name special"
    - from: "S1"
      to: "S3"
      input: "+b"
      event: "Event name special"
    - from: "S2"
      to: "S3"
      input: "b+"
      event: "Event name 02"
    - from: "S3"
      to: "S1"
      input: "c+"
      event: "Back to before"

Machine B:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S1"
      to: "S2"
      input: "+c"
      event: "Event name 03"
    - from: "S2"
      to: "S3"
      input: "+d"
      event: "Event name 04"
    - from: "S3"
      to: "S1"
      input: "+d"
      event: "Back to before"
