Machine A:
  Initial_global_state:
    - "S0"
  States:
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S2"
      input: "-1"
      event: "Sending signal 1"
    - from: "S0"
      to: "S1"
      input: "+3"
      event: "Receving signal 3"
    - from: "S0"
      to: "S2"
      input: "+3"
      event: "Receving signal 3"
    - from: "S1"
      to: "S2"
      input: "+3"
      event: "Receving signal 3"
    - from: "S1"
      to: "S3"
      input: "+4"
      event: "Receving signal 4"
    - from: "S1"
      to: "S2"
      input: "-2"
      event: "Sending signal 2"
    - from: "S3"
      to: "S2"
      input: "+3"
      event: "Receving signal 3"
    - from: "S2"
      to: "S0"
      input: "+3"
      event: "Receving signal 3"
Machine B:
  Initial_global_state:
    - "S0"
  States:
    - "S0"
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S1"
      input: "-3"
      event: "Sending signal 3"
    - from: "S0"
      to: "S2"
      input: "+1"
      event: "Receving signal 1"
    - from: "S1"
      to: "S2"
      input: "+1"
      event: "Receving signal 1"
    - from: "S2"
      to: "S0"
      input: "+2"
      event: "Receving signal 2"
    - from: "S2"
      to: "S3"
      input: "+1"
      event: "Receving signal 1"
    - from: "S3"
      to: "S2"
      input: "-4"
      event: "Sending signal 4"
Machine C:
  Initial_global_state:
    - "S0"
  States:
    - "S0"
    - "S1"
    - "S2"
    - "S3"
  Transitions:
    - from: "S0"
      to: "S1"
      input: "-3"
      event: "Sending signal 3"
    - from: "S0"
      to: "S2"
      input: "+1"
      event: "Receving signal 1"
    - from: "S1"
      to: "S2"
      input: "+1"
      event: "Receving signal 1"
    - from: "S2"
      to: "S0"
      input: "+2"
      event: "Receving signal 2"
    - from: "S2"
      to: "S3"
      input: "+1"
      event: "Receving signal 1"
    - from: "S3"
      to: "S2"
      input: "-4"
      event: "Sending signal 4"
