Machine A:
  Initial_state:
    - "Idle"

Machine B:
  Initial_state:
    - "Idle"

Machine 3:
  Initial_state:
    - "WaitingForAck"

Machine 4:
  Initial_state:
    - "WaitingForAck"

Machine 5:
  Initial_state:
    - "WaitingForAck"

Machine 5:
  Initial_state:
    - "WaitingForAck"

