Machine A:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      event: "-R"
      channel: "Machine B"
    - from: "S2"
      to: "S1"
      event: "+E"
    - from: "S2"
      to: "S1"
      event: "-B"
      channel: "Machine C"
    - from: "S2"
      to: "S1"
      event: "-F"
      channel: "Machine C"
Machine B:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      event: "+B"
    - from: "S2"
      to: "S1"
      event: "-E"
      channel: "Machine A"
    - from: "S0"
      to: "S1"
      event: "-R"
      channel: "Machine C"
Machine C:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      event: "+B"
    - from: "S2"
      to: "S1"
      event: "-E"
      channel: "Machine B"
    - from: "S0"
      to: "S1"
      event: "-F"
      channel: "Machine A"
