Machine A:
  Initial_global_state:
    - "S2"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      input: "-R"
      event: "Sending signal R"
    - from: "S1"
      to: "S1"
      input: "+A"
      event: "Receving signal A"
Machine B:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      input: "+R"
      event: "Receving signal R"
    - from: "S1"
      to: "S2"
      input: "-B"
      event: "Sending signal B"
    - from: "S2"
      to: "S1"
      input: "-A"
      event: "Sending signal A"
