Machine A:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      event: "-R"
      channel: "Machine B"
    - from: "S2"
      to: "S1"
      event: "+A"
      channel: "Machine B"
Machine B:
  Initial_global_state:
    - "S1"
  States:
    - "S1"
    - "S2"
  Transitions:
    - from: "S1"
      to: "S2"
      event: "+R"
      channel: "Machine A"
    - from: "S1"
      to: "S2"
      event: "-B"
      channel: "Machine A"
    - from: "S2"
      to: "S1"
      event: "-A"
      channel: "Machine A"
